
package com.eyelinecom.whoisd.sads2.esdpapi.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.eyelinecom.whoisd.sads2.esdpapi.api.ObjectFactory;
import com.eyelinecom.whoisd.sads2.esdpapi.api.Provider;
import com.eyelinecom.whoisd.sads2.esdpapi.api.XmlService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "configuration", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Configuration {


    /**
     * 
     * @param id
     * @return
     *     returns com.eyelinecom.whoisd.sads2.esdpapi.api.Provider
     * @throws EsdpServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProvider", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.GetProvider")
    @ResponseWrapper(localName = "getProviderResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.GetProviderResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/getProviderRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/getProviderResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/getProvider/Fault/EsdpServiceException")
    })
    public Provider getProvider(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param provider
     * @throws EsdpServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "createProvider", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.CreateProvider")
    @ResponseWrapper(localName = "createProviderResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.CreateProviderResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/createProviderRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/createProviderResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/createProvider/Fault/EsdpServiceException")
    })
    public void createProvider(
        @WebParam(name = "provider", targetNamespace = "")
        Provider provider)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns com.eyelinecom.whoisd.sads2.esdpapi.api.XmlService
     * @throws EsdpServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getService", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.GetService")
    @ResponseWrapper(localName = "getServiceResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.GetServiceResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/getServiceRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/getServiceResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/getService/Fault/EsdpServiceException")
    })
    public XmlService getService(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param provider
     * @throws EsdpServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "updateProvider", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.UpdateProvider")
    @ResponseWrapper(localName = "updateProviderResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.UpdateProviderResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/updateProviderRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/updateProviderResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/updateProvider/Fault/EsdpServiceException")
    })
    public void updateProvider(
        @WebParam(name = "provider", targetNamespace = "")
        Provider provider)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param id
     * @throws EsdpServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProvider", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.DeleteProvider")
    @ResponseWrapper(localName = "deleteProviderResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.DeleteProviderResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/deleteProviderRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/deleteProviderResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/deleteProvider/Fault/EsdpServiceException")
    })
    public void deleteProvider(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param service
     * @throws EsdpServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "createService", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.CreateService")
    @ResponseWrapper(localName = "createServiceResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.CreateServiceResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/createServiceRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/createServiceResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/createService/Fault/EsdpServiceException")
    })
    public void createService(
        @WebParam(name = "service", targetNamespace = "")
        XmlService service)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param service
     * @throws EsdpServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "updateService", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.UpdateService")
    @ResponseWrapper(localName = "updateServiceResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.UpdateServiceResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/updateServiceRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/updateServiceResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/updateService/Fault/EsdpServiceException")
    })
    public void updateService(
        @WebParam(name = "service", targetNamespace = "")
        XmlService service)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param id
     * @throws EsdpServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteService", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.DeleteService")
    @ResponseWrapper(localName = "deleteServiceResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.DeleteServiceResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/deleteServiceRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/deleteServiceResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/deleteService/Fault/EsdpServiceException")
    })
    public void deleteService(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws EsdpServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listServices", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.ListServices")
    @ResponseWrapper(localName = "listServicesResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.ListServicesResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/listServicesRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/listServicesResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/listServices/Fault/EsdpServiceException")
    })
    public List<String> listServices(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws EsdpServiceException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws EsdpServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listProviders", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.ListProviders")
    @ResponseWrapper(localName = "listProvidersResponse", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/", className = "com.eyelinecom.whoisd.sads2.esdpapi.api.ListProvidersResponse")
    @Action(input = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/listProvidersRequest", output = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/listProvidersResponse", fault = {
        @FaultAction(className = EsdpServiceException.class, value = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/configuration/listProviders/Fault/EsdpServiceException")
    })
    public List<String> listProviders(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws EsdpServiceException
    ;

}
