
package com.eyelinecom.whoisd.sads2.esdpapi.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "configuration", targetNamespace = "http://impl.esdpapi.sads2.whoisd.eyelinecom.com/", wsdlLocation = "https://api.miniapps.run/api/esdp/soap-api/conf?wsdl")
public class Configuration_Service
    extends Service
{

    private final static URL CONFIGURATION_WSDL_LOCATION;
    private final static WebServiceException CONFIGURATION_EXCEPTION;
    private final static QName CONFIGURATION_QNAME = new QName("http://impl.esdpapi.sads2.whoisd.eyelinecom.com/", "configuration");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.miniapps.run/api/esdp/soap-api/conf?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONFIGURATION_WSDL_LOCATION = url;
        CONFIGURATION_EXCEPTION = e;
    }

    public Configuration_Service() {
        super(__getWsdlLocation(), CONFIGURATION_QNAME);
    }

    public Configuration_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONFIGURATION_QNAME, features);
    }

    public Configuration_Service(URL wsdlLocation) {
        super(wsdlLocation, CONFIGURATION_QNAME);
    }

    public Configuration_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONFIGURATION_QNAME, features);
    }

    public Configuration_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Configuration_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Configuration
     */
    @WebEndpoint(name = "WebPort")
    public Configuration getWebPort() {
        return super.getPort(new QName("http://impl.esdpapi.sads2.whoisd.eyelinecom.com/", "WebPort"), Configuration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Configuration
     */
    @WebEndpoint(name = "WebPort")
    public Configuration getWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.esdpapi.sads2.whoisd.eyelinecom.com/", "WebPort"), Configuration.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONFIGURATION_EXCEPTION!= null) {
            throw CONFIGURATION_EXCEPTION;
        }
        return CONFIGURATION_WSDL_LOCATION;
    }

}
