
package com.eyelinecom.whoisd.sads2.esdpapi.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EsdpServiceException", targetNamespace = "http://api.esdpapi.sads2.whoisd.eyelinecom.com/")
public class EsdpServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.eyelinecom.whoisd.sads2.esdpapi.api.EsdpServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public EsdpServiceException(String message, com.eyelinecom.whoisd.sads2.esdpapi.api.EsdpServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public EsdpServiceException(String message, com.eyelinecom.whoisd.sads2.esdpapi.api.EsdpServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.eyelinecom.whoisd.sads2.esdpapi.api.EsdpServiceException
     */
    public com.eyelinecom.whoisd.sads2.esdpapi.api.EsdpServiceException getFaultInfo() {
        return faultInfo;
    }

}
